name: Docker

on:
  push:
    # Publish `release` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: kotlang-admin-panel
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Yarn
        run: npm install -g yarn
        
      - name: Install dependencies
        run: yarn
        
      - name: Update package repository
        run: sudo apt update
        
      - name: Install protoc-gen-grpc-web
        run: yarn global add protoc-gen-grpc-web

      - name: Install protobuf compiler
        run: sudo apt install -y protobuf-compiler

      - name: Build
        run: ./build.sh

      - name: Build docker image
        run: docker build -t sainageswar/$IMAGE_NAME:$IMAGE_TAG .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker push sainageswar/$IMAGE_NAME:$IMAGE_TAG
          fi
